### PR TITLE
disable drag and drop on well

### PR DESCRIPTION
**Pull request by ferdinandpolpol**

### CODE REVIEW

**Comment by byshine** [comment]
Is it stable on Juno?
I recall it's no longer stable on all.

**Comment by ferdinandpolpol** [comment]
@byshine Is it not working on every oscar clinics now? https://trello.com/c/aVea6E4s this ticket says it's working on openosp and tht clinics.

**Comment by byshine** [comment]
Yes but it's not stable. Switching appointments between doctors may delete the appointment in some instances.
I guess it's possibly safer to just enable switching between the same doctor.

**Comment by ferdinandpolpol** [comment]
I see, I'll disable switching to other doctors for now then

**Comment by byshine** [comment]
We need to be sure though, even the same doctor might be the case. Were they any reports from clinics?

**Comment by ferdinandpolpol** [comment]
I'll ask the customer success team

**Pull request merged**
